import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/app/[locale]/components/Global/header';
import Footer from '@/app/[locale]/components/Global/footer';
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}
export default async  function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  const messages = await getMessages();
  console.log(locale);
  
  return (
    <html lang={locale} dir={locale!='en'? 'rtl' : 'ltr'}>

      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <Header />
          <div className='pt-[8.5rem]'>{children}</div>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
